create table PatientReg_PatientRegistration (
	uuid_ VARCHAR(75) null,
	patientRegistrationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	address1 VARCHAR(75) null,
	city VARCHAR(75) null,
	state_ VARCHAR(75) null,
	zipCode VARCHAR(75) null,
	emailAddr VARCHAR(75) null,
	dob VARCHAR(75) null,
	optIn INTEGER,
	phoneNumber VARCHAR(75) null,
	pcpFirstName VARCHAR(75) null,
	pcpLastName VARCHAR(75) null,
	pcpAddress VARCHAR(75) null,
	pcpCity VARCHAR(75) null,
	pcpState VARCHAR(75) null,
	pcpZipCode VARCHAR(75) null,
	referringPractice VARCHAR(75) null
);